language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

install:
  - sudo apt-get install cmake
  - wget https://raw.githubusercontent.com/libgit2/pygit2/master/.travis.sh
  - bash .travis.sh
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV
