language: python

matrix:
  include:
  # Create travis test builds using specific tox environment
  - python: 3.5
    env: TOX_ENV=py35
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.7
    env: TOX_ENV=py37
    dist: xenial
  - python: 3.8
    env: TOX_ENV=py38
    dist: xenial
  - python: 3.9
    env: TOX_ENV=py39
    dist: xenial
  - python: 3.10
    env: TOX_ENV=py310
    dist: xenial

install:
  - pip install tox

script: tox -e $TOX_ENV
